//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.04 at 07:38:16 PM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ercot.com/schema/2007-06/nodal/ews/message", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ercot.schema._2007_06.nodal.ews.message;
